namespace Manabot.Modules.Commands.AutoVoice.Themes;

public class Pirates : ITheme
{
    public string GetRandom() => List[new Random().Next(List.Count)];
    private static List<string> List =>
    [
        "Captain’s Quarters",
        "The Crow’s Nest",
        "Jolly Roger",
        "Treasure Cove",
        "Dead Man’s Chest",
        "The Brig",
        "Rum Cellar",
        "Shanty Shack",
        "Mermaid’s Lagoon",
        "The Helm",
        "The Dockyard",
        "The Plank",
        "Stormy Seas",
        "Cutlass Crew",
        "Sea Dog’s Den",
        "Skull Island",
        "Cannon Deck",
        "Parrot Perch",
        "Black Flag",
        "The Shipwreck",
        "Barnacle Bay",
        "The Kracken’s Call",
        "Davy Jones’ Locker",
        "Harpoon Hold",
        "The Compass Rose",
        "Marooner’s Camp",
        "Hidden Treasure",
        "The Buccaneer",
        "The Galleon",
        "Peg Leg Tavern",
        "Sea Serpent’s Lair",
        "The Anchor Drop",
        "Ghost Ship",
        "Corsair’s Quarters",
        "Powder Keg",
        "Golden Doubloons",
        "Map Room",
        "Saltwater Saloon",
        "Captain’s Log",
        "Privateer’s Port",
        "The Shipyard",
        "The Bilge",
        "Rum Runners",
        "Sirens’ Song",
        "Crow’s Call",
        "The Lookout",
        "Sailor’s Rest",
        "The Dockside",
        "The Horizon",
        "High Seas"
    ];
}