//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manabot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandLocales {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandLocales() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Manabot.Resources.CommandLocales", typeof(CommandLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ping_title {
            get {
                return ResourceManager.GetString("ping.title", resourceCulture);
            }
        }
        
        internal static string ping_description {
            get {
                return ResourceManager.GetString("ping.description", resourceCulture);
            }
        }
        
        internal static string autovoice_title {
            get {
                return ResourceManager.GetString("autovoice.title", resourceCulture);
            }
        }
        
        internal static string autovoice_description {
            get {
                return ResourceManager.GetString("autovoice.description", resourceCulture);
            }
        }
        
        internal static string autovoice_button_setup {
            get {
                return ResourceManager.GetString("autovoice.button.setup", resourceCulture);
            }
        }
        
        internal static string autovoice_button_theme {
            get {
                return ResourceManager.GetString("autovoice.button.theme", resourceCulture);
            }
        }
        
        internal static string autovoice_button_limit {
            get {
                return ResourceManager.GetString("autovoice.button.limit", resourceCulture);
            }
        }
        
        internal static string autovoice_button_disable {
            get {
                return ResourceManager.GetString("autovoice.button.disable", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_channel_title {
            get {
                return ResourceManager.GetString("autovoice.theme.channel.title", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_channel_description {
            get {
                return ResourceManager.GetString("autovoice.theme.channel.description", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_channel_select {
            get {
                return ResourceManager.GetString("autovoice.theme.channel.select", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_title {
            get {
                return ResourceManager.GetString("autovoice.theme.select.title", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_description {
            get {
                return ResourceManager.GetString("autovoice.theme.select.description", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_updated_title {
            get {
                return ResourceManager.GetString("autovoice.theme.updated.title", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_updated_description {
            get {
                return ResourceManager.GetString("autovoice.theme.updated.description", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_placeholder {
            get {
                return ResourceManager.GetString("autovoice.theme.select.placeholder", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_theme_description {
            get {
                return ResourceManager.GetString("autovoice.theme.select.theme.description", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_general {
            get {
                return ResourceManager.GetString("autovoice.theme.select.general", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_pirates {
            get {
                return ResourceManager.GetString("autovoice.theme.select.pirates", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_select_finalfantasy {
            get {
                return ResourceManager.GetString("autovoice.theme.select.finalfantasy", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_set_title {
            get {
                return ResourceManager.GetString("autovoice.theme.set.title", resourceCulture);
            }
        }
        
        internal static string autovoice_theme_set_description {
            get {
                return ResourceManager.GetString("autovoice.theme.set.description", resourceCulture);
            }
        }
        
        internal static string autovoice_disable_title {
            get {
                return ResourceManager.GetString("autovoice.disable.title", resourceCulture);
            }
        }
        
        internal static string autovoice_disable_channel_select {
            get {
                return ResourceManager.GetString("autovoice.disable.channel.select", resourceCulture);
            }
        }
        
        internal static string autovoice_disable_description {
            get {
                return ResourceManager.GetString("autovoice.disable.description", resourceCulture);
            }
        }
        
        internal static string autovoice_setup_channel_title {
            get {
                return ResourceManager.GetString("autovoice.setup.channel.title", resourceCulture);
            }
        }
        
        internal static string autovoice_disable_channel_success {
            get {
                return ResourceManager.GetString("autovoice.disable.channel.success", resourceCulture);
            }
        }
        
        internal static string autovoice_setup_channel_description {
            get {
                return ResourceManager.GetString("autovoice.setup.channel.description", resourceCulture);
            }
        }
        
        internal static string autovoice_setup_channel_complete {
            get {
                return ResourceManager.GetString("autovoice.setup.channel.complete", resourceCulture);
            }
        }
        
        internal static string autovoice_setup_channel_voicechannel {
            get {
                return ResourceManager.GetString("autovoice.setup.channel.voicechannel", resourceCulture);
            }
        }
        
        internal static string autovoice_users_title {
            get {
                return ResourceManager.GetString("autovoice.users.title", resourceCulture);
            }
        }
        
        internal static string autovoice_users_description {
            get {
                return ResourceManager.GetString("autovoice.users.description", resourceCulture);
            }
        }
        
        internal static string autovoice_users_voicechannel {
            get {
                return ResourceManager.GetString("autovoice.users.voicechannel", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_title {
            get {
                return ResourceManager.GetString("autovoice.users.select.title", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_description {
            get {
                return ResourceManager.GetString("autovoice.users.select.description", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_limit {
            get {
                return ResourceManager.GetString("autovoice.users.select.limit", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_limit_default {
            get {
                return ResourceManager.GetString("autovoice.users.select.limit.default", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_limit_users {
            get {
                return ResourceManager.GetString("autovoice.users.select.limit.users", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_limit_set_title {
            get {
                return ResourceManager.GetString("autovoice.users.select.limit.set.title", resourceCulture);
            }
        }
        
        internal static string autovoice_users_select_limit_set_description {
            get {
                return ResourceManager.GetString("autovoice.users.select.limit.set.description", resourceCulture);
            }
        }
        
        internal static string autovoice_channel_notfound {
            get {
                return ResourceManager.GetString("autovoice.channel.notfound", resourceCulture);
            }
        }
        
        internal static string autovoice_error_permission {
            get {
                return ResourceManager.GetString("autovoice.error.permission", resourceCulture);
            }
        }
        
        internal static string autovoice_error_channel_exists {
            get {
                return ResourceManager.GetString("autovoice.error.channel.exists", resourceCulture);
            }
        }
        
        internal static string error_duplicate_setting_title {
            get {
                return ResourceManager.GetString("error.duplicate.setting.title", resourceCulture);
            }
        }
        
        internal static string error_duplicate_setting_description {
            get {
                return ResourceManager.GetString("error.duplicate.setting.description", resourceCulture);
            }
        }
        
        internal static string exception_error {
            get {
                return ResourceManager.GetString("exception.error", resourceCulture);
            }
        }
        
        internal static string parse_error {
            get {
                return ResourceManager.GetString("parse.error", resourceCulture);
            }
        }
    }
}
